added functions to get inormation from aws about ec2 instances

diff --git a/link/bashrc b/link/bashrc
--- a/link/bashrc
+++ b/link/bashrc
@@ -14,38 +14,49 @@ done
 
 # https://wiki.archlinux.org/index.php/Color_Bash_Prompt
 set_prompt () {
-		# These override what is in bash-colors
-    Last_Command=$? # Must come first!
-    Blue='\[\e[01;34m\]'
-    White='\[\e[01;37m\]'
-    Red='\[\e[01;31m\]'
-		Green='\[\e[01;32m\]'  
-    Reset='\[\e[00m\]'
-    FancyX='\342\234\227'
-    Checkmark='\342\234\223'
+	# These override what is in bash-colors
+	Last_Command=$? # Must come first!
+	Blue='\[\e[01;34m\]'
+	White='\[\e[01;37m\]'
+	Red='\[\e[01;31m\]'
+	Green='\[\e[01;32m\]'
+	Reset='\[\e[00m\]'
+	FancyX='\342\234\227'
+	Checkmark='\342\234\223'
 
-    # Add a bright white exit status for the last command
-		PS1=""
-    # If it was successful, print a green check mark. Otherwise, print
-    # a red X.
-    if [[ $Last_Command == 0 ]]; then
-        PS1+="$Green$Checkmark "
-    else
-				PS1="$White\$? "
-        PS1+="$Red$FancyX "
-    fi
-    # If root, just print the host in red. Otherwise, print the current user
-    # and host in green.
-    if [[ $EUID == 0 ]]; then
-				PS1+="${Red}root "
-    else
-				PS1+="$Green\u "
-    fi
-    # Print the working directory and prompt marker in blue, and reset
-    # the text color to the default.
-		PS1+="$Blue[ \w ]"
-		
-		PS1+="$White\$(__git_ps1) $Blue\$ $Reset"
+	# Add a bright white exit status for the last command
+	PS1=""
+	# If it was successful, print a green check mark. Otherwise, print
+	# a red X.
+	if [[ $Last_Command == 0 ]]; then
+		PS1+="$Green$Checkmark "
+	else
+		PS1="$White\$? "
+		PS1+="$Red$FancyX "
+	fi
+	# If root, just print the host in red. Otherwise, print the current user
+	# and host in green.
+	if [[ $EUID == 0 ]]; then
+		PS1+="${Red}root "
+	else
+		PS1+="$Green\u "
+	fi
+	# Print the working directory and prompt marker in blue, and reset
+	# the text color to the default.
+	PS1+="$Blue[ \w ]"
+
+	PS1+="$White\$(__git_ps1) $Blue\$ $Reset"
 }
 PROMPT_COMMAND='set_prompt'
 
+function hostname_from_instance() {
+	echo $(aws ec2 describe-instances --filters "{\"Name\":\"tag:Name\", \"Values\":[\"$1\"]}" --query='Reservations[0].Instances[0].PublicDnsName' | tr -d '"')
+}
+
+function ip_from_instance() {
+	echo $(aws ec2 describe-instances --filters "{\"Name\":\"tag:Name\", \"Values\":[\"$1\"]}" --query='Reservations[0].Instances[0].PublicIpAddress' | tr -d '"')
+}
+
+function ssh-aws() {
+	ssh "$2"@$(ip_from_instance "$1")
+}
