changed up some stuff

diff --git a/link/bashrc b/link/bashrc
--- a/link/bashrc
+++ b/link/bashrc
@@ -4,6 +4,42 @@ alias ls='ls -F --color=auto'
 alias grep='grep --color=auto'
 alias ll='ls -l'
 
-for file in ~/dotfiles/source/*;  do
-	source $file
+for file in ~/dotfiles/source/*; do
+	source "$file"
 done
+
+set_prompt () {
+    Last_Command=$? # Must come first!
+    Blue='\[\e[01;34m\]'
+    White='\[\e[01;37m\]'
+    Red='\[\e[01;31m\]'
+    Green='\[\e[01;32m\]'
+    Reset='\[\e[00m\]'
+    FancyX='\342\234\227'
+    Checkmark='\342\234\223'
+
+    # Add a bright white exit status for the last command
+		PS1=""
+    # If it was successful, print a green check mark. Otherwise, print
+    # a red X.
+    if [[ $Last_Command == 0 ]]; then
+        PS1+="$Green$Checkmark "
+    else
+				PS1="$White\$? "
+        PS1+="$Red$FancyX "
+    fi
+    # If root, just print the host in red. Otherwise, print the current user
+    # and host in green.
+    if [[ $EUID == 0 ]]; then
+				PS1+="${Red}root "
+    else
+				PS1+="$Green\u "
+    fi
+    # Print the working directory and prompt marker in blue, and reset
+    # the text color to the default.
+		PS1+="$Blue\w "
+		
+		PS1+="$White\$(__git_ps1) $Blue\$ $Reset"
+}
+PROMPT_COMMAND='set_prompt'
+
